apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: main-claster
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - protocol: TCP
      # name: https
      port: 3000
      # targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana 
        image: grafana-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000