apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: main-claster
spec:
  selector:
    app: php
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: https
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php 
        image: php-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000