apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: main-claster
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
   - protocol: TCP
     name: ftpser
     port: 21
     targetPort: 21
   - protocol: TCP
     name: ftps
     port: 30021
     targetPort: 30021
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps 
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30021